# Workflow that runs on code changes to a pull request.

name: Any changes
on:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Check formatting
          uses: "lgeiger/black-action@master"
          with:
            args: ". -l 79 --check"
  Test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'
            
        - name: Install package
          run: make install
        
        - name: Test documentation builds
          run: make documentation