# Workflow that runs on code changes to a pull request.

name: Any changes
on:
  pull_request:
    branches:
      - main

jobs:
  docs:
      name: Test documentation builds
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Install uv
          uses: astral-sh/setup-uv@v5

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'
              
        - name: Install package
          run: uv pip install .[dev] --system
        
        - name: Test documentation builds
          run: make documentation
          env:
            HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}

        - name: Check documentation build
          run: |
            for notebook in $(find docs/_build/jupyter_execute -name "*.ipynb"); do
              if grep -q '"output_type": "error"' "$notebook"; then
                echo "Error found in $notebook"
                cat "$notebook"
                exit 1
              fi
            done