# Workflow that runs on code changes to a pull request.

name: Any changes
on:
  pull_request:
    branches:
      - main

jobs:
  docs:
      permissions:
        contents: "read"
        id-token: "write"
      name: Test documentation builds
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Install uv
          uses: astral-sh/setup-uv@v5

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'
        - uses: "google-github-actions/auth@v2"
          with:
            workload_identity_provider: "projects/322898545428/locations/global/workloadIdentityPools/policyengine-research-id-pool/providers/prod-github-provider"
            service_account: "policyengine-research@policyengine-research.iam.gserviceaccount.com"
              
        - name: Install package
          run: uv pip install .[dev] --system
        
        - name: Test documentation builds
          run: make documentation

        - name: Check documentation build
          run: |
            for notebook in $(find docs/_build/jupyter_execute -name "*.ipynb"); do
              if grep -q '"output_type": "error"' "$notebook"; then
                echo "Error found in $notebook"
                cat "$notebook"
                exit 1
              fi
            done