name: Pull request
on:
  pull_request:
    branches: [ main ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        
      - name: Install package
        run: make install
      
      - name: Install dependencies
        run: |
          pip install jupyter-book
          pip install furo
          pip install sphinx-argparse
      
      - name: Generate documentation
        run: make documentation
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}

      - name: Check documentation build
        run: |
          for notebook in $(find docs/_build/jupyter_execute -name "*.ipynb"); do
            if grep -q '"output_type": "error"' "$notebook"; then
              echo "Error found in $notebook"
              cat "$notebook"
              exit 1
            fi
          done
