# Workflow that runs on code changes to a pull request.

name: Docs changes
on:
  pull_request:
    branches:
      - main

    paths:
      - docs/**
      - .github/**
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Test documentation builds
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install MyST
        run: npm install -g mystmd
      - name: Test documentation builds
        run: cd docs && myst build --html
