name: Publish package
on:
  push:
    branches: [ main ]
    paths:
        - pyproject.toml

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Publish a git tag
        run: ".github/publish-git-tag.sh || true"
      - name: Install package
        run: make install
      - name: Build package
        run: make
      - name: Remove .whl files
        run: rm dist/*.whl
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
          skip-existing: true
          verbose: true
        
      - name: Test documentation builds
        run: make documentation
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
      
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
